# Generated by Django 5.2.14 on 2026-05-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_reason', models.TextField(blank=True, null=True, verbose_name='판매 인기 요인')),
                ('review_summary', models.TextField(blank=True, null=True, verbose_name='리뷰 요약')),
                ('status', models.CharField(choices=[('pending', '대기'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='books.book', verbose_name='도서')),
            ],
            options={
                'verbose_name': 'AI 요약',
                'verbose_name_plural': 'AI 요약 목록',
                'db_table': 'ai_summary',
            },
        ),
    ]
