# Generated by Django 5.2.14 on 2026-05-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_recommend_reason', models.TextField(blank=True, null=True, verbose_name='추천 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='books.book', verbose_name='도서')),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='trends.trendissue', verbose_name='트렌드')),
            ],
            options={
                'verbose_name': '추천',
                'verbose_name_plural': '추천 목록',
                'db_table': 'recommendation',
                'constraints': [models.UniqueConstraint(fields=('trend', 'book'), name='uq_recommendation_trend_book')],
            },
        ),
    ]
