# Generated by Django 5.2.14 on 2026-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='이슈 제목')),
                ('summary', models.TextField(verbose_name='요약 내용')),
                ('category', models.CharField(choices=[('POLITICS', '정치'), ('ECONOMY', '경제'), ('TECH', '기술'), ('CULTURE', '문화'), ('WEATHER', '날씨')], max_length=20, verbose_name='카테고리')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='수집 출처')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수집 일시')),
            ],
            options={
                'verbose_name': '트렌드 이슈',
                'verbose_name_plural': '트렌드 이슈 목록',
                'db_table': 'trend_issue',
                'indexes': [models.Index(fields=['category'], name='idx_trend_category'), models.Index(fields=['-created_at'], name='idx_trend_created')],
            },
        ),
    ]
