# Generated by Django 5.2.14 on 2026-06-22 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendissue',
            name='cache_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='외부 데이터 식별자'),
        ),
        migrations.AddField(
            model_name='trendissue',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='부가 정보'),
        ),
        migrations.AddField(
            model_name='trendissue',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='원문 발행 시각'),
        ),
        migrations.AddField(
            model_name='trendissue',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='원문 URL'),
        ),
        migrations.AddField(
            model_name='trendissue',
            name='synced_on',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='동기화 기준일'),
        ),
        migrations.AddIndex(
            model_name='trendissue',
            index=models.Index(fields=['synced_on', 'category'], name='idx_trend_sync_category'),
        ),
    ]
