# Generated by Django 5.2.14 on 2026-05-15 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, verbose_name='도서명')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='저자')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='출판사')),
                ('cover_img', models.URLField(blank=True, max_length=500, null=True, verbose_name='표지 URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='줄거리')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리명')),
                ('aladin_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='알라딘 링크')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='출판일')),
                ('cached_at', models.DateTimeField(auto_now_add=True, verbose_name='캐싱 시점')),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서 목록',
                'db_table': 'book',
                'indexes': [models.Index(fields=['isbn'], name='idx_book_isbn'), models.Index(fields=['title'], name='idx_book_title')],
            },
        ),
        migrations.CreateModel(
            name='BookBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='찜한 일시')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.book', verbose_name='도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜 목록',
                'db_table': 'book_bookmark',
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='uq_bookmark_user_book')],
            },
        ),
    ]
