# Generated by Django 5.2.14 on 2026-06-22 01:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AladinCategory',
            fields=[
                ('cid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='알라딘 CID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('mall_type', models.CharField(choices=[('BOOK', '국내도서'), ('FOREIGN', '외국도서'), ('EBOOK', '전자책')], db_index=True, max_length=10, verbose_name='몰 유형')),
                ('depth1', models.CharField(max_length=100, verbose_name='1단계')),
                ('depth2', models.CharField(blank=True, default='', max_length=100, verbose_name='2단계')),
                ('depth3', models.CharField(blank=True, default='', max_length=100, verbose_name='3단계')),
                ('depth4', models.CharField(blank=True, default='', max_length=100, verbose_name='4단계')),
                ('depth5', models.CharField(blank=True, default='', max_length=100, verbose_name='5단계')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '알라딘 카테고리',
                'verbose_name_plural': '알라딘 카테고리 목록',
                'db_table': 'aladin_category',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='대표 카테고리 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='연결일')),
            ],
            options={
                'verbose_name': '도서 카테고리',
                'verbose_name_plural': '도서 카테고리 목록',
                'db_table': 'book_category',
            },
        ),
        migrations.CreateModel(
            name='BookRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('BESTSELLER', '베스트셀러'), ('ITEM_NEW_ALL', '신간 전체'), ('ITEM_NEW_SPECIAL', '주목할 만한 신간'), ('EDITOR_CHOICE', '편집자 추천'), ('BLOG_BEST', '블로거 베스트셀러')], max_length=20, verbose_name='리스트 유형')),
                ('rank', models.PositiveIntegerField(verbose_name='순위')),
                ('period_start', models.DateField(verbose_name='집계 기준일')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='수집 시점')),
            ],
            options={
                'verbose_name': '도서 순위',
                'verbose_name_plural': '도서 순위 이력',
                'db_table': 'book_ranking',
                'ordering': ('-period_start', 'rank'),
            },
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='idx_book_isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='adult',
            field=models.BooleanField(default=False, verbose_name='성인 등급'),
        ),
        migrations.AddField(
            model_name='book',
            name='aladin_item_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='알라딘 상품 ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='customer_review_rank',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='회원 리뷰 평점'),
        ),
        migrations.AddField(
            model_name='book',
            name='fixed_price',
            field=models.BooleanField(default=False, verbose_name='도서 정가제 대상'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn10',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ISBN10'),
        ),
        migrations.AddField(
            model_name='book',
            name='mall_type',
            field=models.CharField(choices=[('BOOK', '국내도서'), ('FOREIGN', '외국도서'), ('EBOOK', '전자책')], db_index=True, default='BOOK', max_length=10, verbose_name='몰 유형'),
        ),
        migrations.AddField(
            model_name='book',
            name='price_sales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='판매가'),
        ),
        migrations.AddField(
            model_name='book',
            name='price_standard',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='정가'),
        ),
        migrations.AddField(
            model_name='book',
            name='sales_point',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='판매지수'),
        ),
        migrations.AddField(
            model_name='book',
            name='stock_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='재고 상태'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 갱신 시점'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='저자'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cached_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='최초 캐싱 시점'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_name',
            field=models.CharField(blank=True, help_text='API 응답 표시용 캐시. 정식 관계는 categories를 사용합니다.', max_length=100, null=True, verbose_name='대표 카테고리명'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, verbose_name='ISBN13'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='출판사'),
        ),
        migrations.AddIndex(
            model_name='aladincategory',
            index=models.Index(fields=['mall_type', 'name'], name='idx_category_mall_name'),
        ),
        migrations.AddIndex(
            model_name='aladincategory',
            index=models.Index(fields=['mall_type', 'depth1'], name='idx_category_mall_d1'),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='books.book', verbose_name='도서'),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_links', to='books.aladincategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', through='books.BookCategory', to='books.aladincategory'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['mall_type', 'pub_date'], name='idx_book_mall_pubdate'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-sales_point'], name='idx_book_sales_point'),
        ),
        migrations.AddField(
            model_name='bookranking',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='books.book', verbose_name='도서'),
        ),
        migrations.AddField(
            model_name='bookranking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rankings', to='books.aladincategory', verbose_name='조회 카테고리'),
        ),
        migrations.AddConstraint(
            model_name='bookcategory',
            constraint=models.UniqueConstraint(fields=('book', 'category'), name='uq_book_category'),
        ),
        migrations.AddConstraint(
            model_name='bookcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('book',), name='uq_book_primary_category'),
        ),
        migrations.AddIndex(
            model_name='bookranking',
            index=models.Index(fields=['list_type', 'category', '-period_start', 'rank'], name='idx_ranking_lookup'),
        ),
        migrations.AddConstraint(
            model_name='bookranking',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='ck_book_ranking_positive'),
        ),
        migrations.AddConstraint(
            model_name='bookranking',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('book', 'category', 'list_type', 'period_start'), name='uq_book_ranking_category'),
        ),
        migrations.AddConstraint(
            model_name='bookranking',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('book', 'list_type', 'period_start'), name='uq_book_ranking_all'),
        ),
    ]
