# Generated by Django 5.2.14 on 2026-06-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_aladincategory_bookcategory_bookranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBN13'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('isbn', 'mall_type'), name='uq_book_isbn_malltype'),
        ),
    ]
